version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3010:3010"
    depends_on:
      - db
    # コンテナ起動を続けるため
    tty: true
    #標準出力とエラー出力を結びつける
    stdin_open: true
  db:
    image: mysql
    # M1 CPUのためにplatform指定
    platform: linux/amd64
    # DBのレコードが日本語だと文字化けするので、utf8をセットする
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    # 環境変数
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: databese
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
volumes:
  db-volume:
