name: Run rspec, rubocop

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    services:
      db:
        image: mysql
        ports:
          - 3306:3306
        env:
          LANG: "ja_JP.UTF-8"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_USER: root
          MYSQL_DATABASE: myapp_development
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

    steps:
      # 該当ブランチをcheckout
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      # migrationの実施
      - name: DB migration
        env:
          DB_HOST: 127.0.0.1
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      # RSpec
      - name: Run Rspec
        run: bundle exec rspec
      
      # Rubocop
      - name: Run Rubocop
        run: bundle exec rubocop
