name: Rails-ci

on:
  push:
    branches:
      - "**"

jobs:
  Rspec_Rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RAILS_ENV: test
    
    services:
      db:
        image: mysql
        ports:
          - 3306:3306
        env:
          LANG: "ja_JP.UTF-8"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

    steps:
      # 該当ブランチをcheckout
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      # migrationの実施
      - name: DB migration
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate

      # RSpec
      - name: Run Rspec
        run: bundle exec rspec
      
      # Rubocop
      - name: Run Rubocop
        run: bundle exec rubocop
